config/routes.rb
BookMyRoom::Application.routes.draw do
  get "users/new"

  root 'bookmyroom#home'
  match '/contact', to: 'bookmyroom#contact', via: 'get'
  match '/room', to: 'bookmyroom#room', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  resources :meeting_rooms

  resources :users

end

app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :meeting_rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmyroom_controller.rb
class BookmyroomController < ApplicationController
  def home
  end

  def contact
  end

  def room
  end
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :set_meeting_room, only: [:show, :edit, :update, :destroy]

  # GET /meeting_rooms
  # GET /meeting_rooms.json
  def index
    @meeting_rooms = MeetingRoom.all
  end

  # GET /meeting_rooms/1
  # GET /meeting_rooms/1.json
  def show
  end

  # GET /meeting_rooms/new
  def new
    @meeting_room = MeetingRoom.new
  end

  # GET /meeting_rooms/1/edit
  def edit
  end

  # POST /meeting_rooms
  # POST /meeting_rooms.json
  def create
    @meeting_room = MeetingRoom.new(meeting_room_params)

    respond_to do |format|
      if @meeting_room.save
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting_room }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_rooms/1
  # PATCH/PUT /meeting_rooms/1.json
  def update
    respond_to do |format|
      if @meeting_room.update(meeting_room_params)
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_rooms/1
  # DELETE /meeting_rooms/1.json
  def destroy
    @meeting_room.destroy
    respond_to do |format|
      format.html { redirect_to meeting_rooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_room
      @meeting_room = MeetingRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_room_params
      params.require(:meeting_room).permit(:room_name, :attendees, :booking_from, :booking_to, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :dept)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "BookMyRoom - Conference Room Booking Application"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/bookmyroom_helper.rb
module BookmyroomHelper
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmyroom/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Find me in app/views/bookmyroom/contact.html.erb</p>

app/views/bookmyroom/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
	<p>Welcome to <h1>BookMyRoom!!!</h1></p>

  <h2>	Conference Room Booking Application  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

  <%= link_to "Available Rooms", room_path, class: "btn btn-large btn-primary" %>


	<div class="right">
		<h6>Powered by</h6>
		<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
	</div>
</div>

app/views/bookmyroom/room.html.erb
<% provide(:title, 'Rooms') %>
<h1>Room's Available</h1>
<p>Find me in app/views/bookmyroom/room.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.etouch.net/home/index.html">eTouch Systems Pvt. Ltd</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "BookMyRoom", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            	<li><%= link_to "Home",  root_path %></li>
          	<li><%= link_to "Sign in", '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
</header> 

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>

</head>
 <body>
 	<%= render 'layouts/header' %>
   
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/meeting_rooms/_form.html.erb
<%= form_for(@meeting_room) do |f| %>
  <% if @meeting_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting_room.errors.count, "error") %> prohibited this meeting_room from being saved:</h2>

      <ul>
      <% @meeting_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_name %><br>
    <%= f.text_field :room_name %>
  </div>
  <div class="field">
    <%= f.label :attendees %><br>
    <%= f.text_field :attendees %>
  </div>
  <div class="field">
    <%= f.label :booking_from %><br>
    <%= f.text_field :booking_from %>
  </div>
  <div class="field">
    <%= f.label :booking_to %><br>
    <%= f.text_field :booking_to %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meeting_rooms/edit.html.erb
<h1>Editing meeting_room</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting_room %> |
<%= link_to 'Back', meeting_rooms_path %>

app/views/meeting_rooms/index.html.erb
<h1>Listing meeting_rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room name</th>
      <th>Attendees</th>
      <th>Booking from</th>
      <th>Booking to</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_rooms.each do |meeting_room| %>
      <tr>
        <td><%= meeting_room.room_name %></td>
        <td><%= meeting_room.attendees %></td>
        <td><%= meeting_room.booking_from %></td>
        <td><%= meeting_room.booking_to %></td>
        <td><%= meeting_room.user_id %></td>
        <td><%= link_to 'Show', meeting_room %></td>
        <td><%= link_to 'Edit', edit_meeting_room_path(meeting_room) %></td>
        <td><%= link_to 'Destroy', meeting_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting room', new_meeting_room_path %>

app/views/meeting_rooms/new.html.erb
<h1>New meeting_room</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_rooms_path %>

app/views/meeting_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room name:</strong>
  <%= @meeting_room.room_name %>
</p>

<p>
  <strong>Attendees:</strong>
  <%= @meeting_room.attendees %>
</p>

<p>
  <strong>Booking from:</strong>
  <%= @meeting_room.booking_from %>
</p>

<p>
  <strong>Booking to:</strong>
  <%= @meeting_room.booking_to %>
</p>

<p>
  <strong>User:</strong>
  <%= @meeting_room.user_id %>
</p>

<%= link_to 'Edit', edit_meeting_room_path(@meeting_room) %> |
<%= link_to 'Back', meeting_rooms_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.text_field :dept %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dept</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.dept %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>New user - Sign up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @user.dept %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>